export const SQLITE3_MODULE_OPTIONS_TOKEN = 'SQLITE3_MODULE_OPTIONS_TOKEN';

export const SQLITE3_CONNECTION_POOL_TOKEN_PREFIX = 'SQLITE3_CONNECTION_POOL.';

export const SQLITE3_ENTITY_MANAGER_TOKEN_PREFIX = 'SQLITE3_ENTITY_MANAGER.';

export const SQLITE3_REPOSITORY_TOKEN_PREFIX = 'SQLITE3_REPOSITORY.';

export const SQLITE3_DEFAULT_CONNECTION_NAME = 'default';
