export const AUTHENTICATION_MODULE_OPTIONS_TOKEN = 'AUTHENTICATION_MODULE_OPTIONS_TOKEN';
export const DEFAULT_BCRYPT_ROUNDS = 10;
export const DEFAULT_SESSION_NAME = 'sessionId';
export const DEFAULT_SESSION_SECRET = 'hot';
export const DEFAULT_SESSION_MAX_AGE = 900000;
